<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kenedith. M. Méndez Gutiérrez">
<meta name="dcterms.date" content="2024-11-06">

<title>Tests para contrastes de hipótesis multivariados entre poblaciones con RStudio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="MAVOVA-perMANOVA_RStudio_files/libs/clipboard/clipboard.min.js"></script>
<script src="MAVOVA-perMANOVA_RStudio_files/libs/quarto-html/quarto.js"></script>
<script src="MAVOVA-perMANOVA_RStudio_files/libs/quarto-html/popper.min.js"></script>
<script src="MAVOVA-perMANOVA_RStudio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MAVOVA-perMANOVA_RStudio_files/libs/quarto-html/anchor.min.js"></script>
<link href="MAVOVA-perMANOVA_RStudio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MAVOVA-perMANOVA_RStudio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MAVOVA-perMANOVA_RStudio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MAVOVA-perMANOVA_RStudio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MAVOVA-perMANOVA_RStudio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenido</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#qué-es-manova" id="toc-qué-es-manova" class="nav-link" data-scroll-target="#qué-es-manova"><span class="header-section-number">1.1</span> ¿Qué es MANOVA?</a>
  <ul class="collapse">
  <li><a href="#objetivos-del-análisis" id="toc-objetivos-del-análisis" class="nav-link" data-scroll-target="#objetivos-del-análisis"><span class="header-section-number">1.1.1</span> Objetivos del análisis</a></li>
  <li><a href="#consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica." id="toc-consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica." class="nav-link" data-scroll-target="#consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica."><span class="header-section-number">1.1.2</span> Consideraciones para aplicar el análisis a una matriz de datos básica.</a></li>
  </ul></li>
  <li><a href="#qué-es-per-manova" id="toc-qué-es-per-manova" class="nav-link" data-scroll-target="#qué-es-per-manova"><span class="header-section-number">1.2</span> ¿Qué es per-MANOVA?</a>
  <ul class="collapse">
  <li><a href="#objetivos-del-análisis-1" id="toc-objetivos-del-análisis-1" class="nav-link" data-scroll-target="#objetivos-del-análisis-1"><span class="header-section-number">1.2.1</span> Objetivos del análisis</a></li>
  <li><a href="#consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica.-1" id="toc-consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica.-1" class="nav-link" data-scroll-target="#consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica.-1"><span class="header-section-number">1.2.2</span> Consideraciones para aplicar el análisis a una matriz de datos básica.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#materiales." id="toc-materiales." class="nav-link" data-scroll-target="#materiales."><span class="header-section-number">2</span> Materiales.</a></li>
  <li><a href="#pasos-previos." id="toc-pasos-previos." class="nav-link" data-scroll-target="#pasos-previos."><span class="header-section-number">3</span> Pasos previos.</a>
  <ul class="collapse">
  <li><a href="#cargue-las-líbrerías." id="toc-cargue-las-líbrerías." class="nav-link" data-scroll-target="#cargue-las-líbrerías."><span class="header-section-number">3.1</span> 1. Cargue las líbrerías.</a></li>
  <li><a href="#importe-los-datos." id="toc-importe-los-datos." class="nav-link" data-scroll-target="#importe-los-datos."><span class="header-section-number">3.2</span> 2. Importe los datos.</a></li>
  </ul></li>
  <li><a href="#análisis-de-varianza-multivariado-manova" id="toc-análisis-de-varianza-multivariado-manova" class="nav-link" data-scroll-target="#análisis-de-varianza-multivariado-manova"><span class="header-section-number">4</span> Análisis de varianza multivariado (MANOVA)</a>
  <ul class="collapse">
  <li><a href="#paso-1.-verificación-de-los-supuesto-ó-requerimientos." id="toc-paso-1.-verificación-de-los-supuesto-ó-requerimientos." class="nav-link" data-scroll-target="#paso-1.-verificación-de-los-supuesto-ó-requerimientos."><span class="header-section-number">4.1</span> Paso 1. Verificación de los supuesto ó requerimientos.</a>
  <ul class="collapse">
  <li><a href="#supuesto-de-normalidad-p-variante-por-grupo." id="toc-supuesto-de-normalidad-p-variante-por-grupo." class="nav-link" data-scroll-target="#supuesto-de-normalidad-p-variante-por-grupo."><span class="header-section-number">4.1.1</span> Supuesto de normalidad p-variante por grupo.</a></li>
  <li><a href="#supuesto-de-homocedasticidad-de-las-matrices-var--cov." id="toc-supuesto-de-homocedasticidad-de-las-matrices-var--cov." class="nav-link" data-scroll-target="#supuesto-de-homocedasticidad-de-las-matrices-var--cov."><span class="header-section-number">4.1.2</span> Supuesto de homocedasticidad de las matrices var- cov.</a></li>
  <li><a href="#supuesto-de-linealidad-y-multicolinealidad." id="toc-supuesto-de-linealidad-y-multicolinealidad." class="nav-link" data-scroll-target="#supuesto-de-linealidad-y-multicolinealidad."><span class="header-section-number">4.1.3</span> Supuesto de linealidad y multicolinealidad.</a></li>
  <li><a href="#supuesto-de-datos-atípicos-influyentes." id="toc-supuesto-de-datos-atípicos-influyentes." class="nav-link" data-scroll-target="#supuesto-de-datos-atípicos-influyentes."><span class="header-section-number">4.1.4</span> Supuesto de datos atípicos influyentes.</a></li>
  </ul></li>
  <li><a href="#paso-2.-efecución-del-algoritmo." id="toc-paso-2.-efecución-del-algoritmo." class="nav-link" data-scroll-target="#paso-2.-efecución-del-algoritmo."><span class="header-section-number">4.2</span> Paso 2. Efecución del algoritmo.</a>
  <ul class="collapse">
  <li><a href="#tabla-de-manova." id="toc-tabla-de-manova." class="nav-link" data-scroll-target="#tabla-de-manova."><span class="header-section-number">4.2.1</span> Tabla de MANOVA.</a></li>
  <li><a href="#contrastes-múltiples." id="toc-contrastes-múltiples." class="nav-link" data-scroll-target="#contrastes-múltiples."><span class="header-section-number">4.2.2</span> Contrastes múltiples.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análisis-de-varianza-multivariado-permutacional-permanova." id="toc-análisis-de-varianza-multivariado-permutacional-permanova." class="nav-link" data-scroll-target="#análisis-de-varianza-multivariado-permutacional-permanova."><span class="header-section-number">5</span> Análisis de varianza multivariado permutacional (perMANOVA).</a>
  <ul class="collapse">
  <li><a href="#pasos-previos.-1" id="toc-pasos-previos.-1" class="nav-link" data-scroll-target="#pasos-previos.-1"><span class="header-section-number">5.1</span> Pasos previos.</a>
  <ul class="collapse">
  <li><a href="#cargue-las-líbrerías.-1" id="toc-cargue-las-líbrerías.-1" class="nav-link" data-scroll-target="#cargue-las-líbrerías.-1"><span class="header-section-number">5.1.1</span> 1. Cargue las líbrerías.</a></li>
  <li><a href="#importe-los-datos.-1" id="toc-importe-los-datos.-1" class="nav-link" data-scroll-target="#importe-los-datos.-1"><span class="header-section-number">5.1.2</span> 2. Importe los datos.</a></li>
  </ul></li>
  <li><a href="#paso-1.-verificación-del-supuestos." id="toc-paso-1.-verificación-del-supuestos." class="nav-link" data-scroll-target="#paso-1.-verificación-del-supuestos."><span class="header-section-number">5.2</span> Paso 1. Verificación del supuestos.</a>
  <ul class="collapse">
  <li><a href="#supuesto-de-normalidad-p-variante-por-grupo.-1" id="toc-supuesto-de-normalidad-p-variante-por-grupo.-1" class="nav-link" data-scroll-target="#supuesto-de-normalidad-p-variante-por-grupo.-1"><span class="header-section-number">5.2.1</span> 1.1 Supuesto de normalidad p variante por grupo.</a></li>
  <li><a href="#supuesto-de-homocedasticidad-p-variante." id="toc-supuesto-de-homocedasticidad-p-variante." class="nav-link" data-scroll-target="#supuesto-de-homocedasticidad-p-variante."><span class="header-section-number">5.2.2</span> 1.2 Supuesto de homocedasticidad p variante.</a></li>
  </ul></li>
  <li><a href="#paso-2.-efecución-del-algoritmo" id="toc-paso-2.-efecución-del-algoritmo" class="nav-link" data-scroll-target="#paso-2.-efecución-del-algoritmo"><span class="header-section-number">5.3</span> Paso 2. Efecución del algoritmo</a>
  <ul class="collapse">
  <li><a href="#tabla-de-per-manova." id="toc-tabla-de-per-manova." class="nav-link" data-scroll-target="#tabla-de-per-manova."><span class="header-section-number">5.3.1</span> Tabla de per-MANOVA.</a></li>
  <li><a href="#contrastes-múltiples.-1" id="toc-contrastes-múltiples.-1" class="nav-link" data-scroll-target="#contrastes-múltiples.-1"><span class="header-section-number">5.3.2</span> Contrastes múltiples.</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#práctica." id="toc-práctica." class="nav-link" data-scroll-target="#práctica."><span class="header-section-number">6</span> Práctica.</a></li>
  <li><a href="#material-complementario-para-profundizar." id="toc-material-complementario-para-profundizar." class="nav-link" data-scroll-target="#material-complementario-para-profundizar."><span class="header-section-number">7</span> Material complementario para profundizar.</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tests para contrastes de hipótesis multivariados entre poblaciones con RStudio</h1>
<p class="subtitle lead">Análisis de varianza multivariante MANOVA &amp; perMANOVA</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kenedith. M. Méndez Gutiérrez </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 6, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<style type="text/css">
  body{
  font-family: Georgia;
  font-size: 12pt;
  text-align: justify;
}
  h1 {
  color: #4C56AC;
  font-size: 20pt;
  font-family: Georgia;
  text-align: left;
  font-weight: blod;
}
  h2 {
  color: #8A4CAC;
  font-size:14pt;
  font-family: Georgia;
  text-align: left;
  font-weight: blod;
}
  h3{ 
  color: #black;
  font-size:13pt;
  font-family: Georgia;
  text-align: left;
  font-weight: blod;
}
</style>
<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Las técnicas de contrastes de hipótesis multivariadas son una extensión de las pruebas con las que se buscar determinar difrencias significativas entre las medias ó medias entre varias poblaciones. En el caso multivariante estas diferencias que se pretenden determinar va dirigida a los vectores de medias entre dos o más poblaciones (grupos). Estas pruebas tienen la particularidad de involucrar una variable independiente de naturaleza cualitativa para distringuir las poblaciones ó grupos y mínimo un par de variables dependientes de naturaleza cuantitativa.</p>
<p>Entre las técnicas de contraste que se emplean con más frecuencias se encuentran el análisis de varianza multivariado (MANOVA) y el análisis de varianza multivariado permutacional (perMANOVA). La escogencia entre alguna de las dos técnicas esta supeditada al cumplimiento de los supuestos.</p>
<section id="qué-es-manova" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="qué-es-manova"><span class="header-section-number">1.1</span> ¿Qué es MANOVA?</h2>
<p>El análisis de varianza multivariado - MANOVA, es un método estadístico multivariante inferencial parámetrico que surge como una una extensión del ANOVA. Está técnica permite analizar el efecto que ejerce sobre varias variables dependientes (o endógenas) métricas una o más variables independientes (o exógenas) no métricas.</p>
<section id="objetivos-del-análisis" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="objetivos-del-análisis"><span class="header-section-number">1.1.1</span> Objetivos del análisis</h3>
<ul>
<li>Contrastar si los valores no métricos de las variables independientes determinarán la igualdad de vectores de medias de una serie de variables dependientes.</li>
</ul>
</section>
<section id="consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica." class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica."><span class="header-section-number">1.1.2</span> Consideraciones para aplicar el análisis a una matriz de datos básica.</h3>
<p>Para poder aplicar el análisis es importante:</p>
<ol type="1">
<li>Tener más de una variable de respuesta ó dependiente a comparar.</li>
<li>verificar que el conjunto de variables dependientes a comparar se ajuste a la distribución normal p-variante para cada población.</li>
<li>verificar si existe igualdad en las matrices de varianza - covarianza de las poblaciones a considerar.</li>
<li>verificar que exista linealidad entre las variables dependientes sin evidencia de multicolinealidad al 100%.</li>
<li>verificar que no existan datos atípicos influyentes.</li>
</ol>
</section>
</section>
<section id="qué-es-per-manova" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="qué-es-per-manova"><span class="header-section-number">1.2</span> ¿Qué es per-MANOVA?</h2>
<p>El Análisis de varianza multivariado permutacional es un método semiparamétrico que conserva importantes propiedades estadísticas robustas de los métodos multivariados no paramétricos basados en rangos. Tiene la flexibilidad de basar el análisis en una medida de disimilitud a elección (como Bray-Curtis, Jaccard, etc.) y de lograr inferencias sin suposición de normalidad multivariante. Por lo tanto, el per-MANOVA es una opción que permite dar respuesta de manera formal a diseños experimentales complejos en una amplia variedad de contextos especialemnte donde:</p>
<ul>
<li><p>Puede haber más variables de respuesta que unidades de muestreo.</p></li>
<li><p>Los datos no se ajustan a la normal multivariante.</p></li>
<li><p>El conjunto de datos estan inflados en cero, poseer datos ordinales o cualitativos (ej., respuestas a cuestionarios, secuencias de ADN / ARN, frecuencias alélicas, aminoácidos ácidos o datos de proteínas).</p></li>
</ul>
<p>Aunque originalmente fue motivado por estudios ecológicos, donde las variables generalmente consisten en conteos de abundancias (o porcentaje de cobertura, frecuencias o biomasa) para un gran número de especies facilitando el análisis de la diversidad beta en múltiples escalas espaciales o temporales, el PERMANOVA en la actualidad se usa en muchos campos, incluyendo química, ciencias sociales, agricultura, medicina, genética, psicología, economía y más.</p>
<section id="objetivos-del-análisis-1" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="objetivos-del-análisis-1"><span class="header-section-number">1.2.1</span> Objetivos del análisis</h3>
<ul>
<li>Contrastar si hay diferencias significativas entre dos o más grupos para al menos 2 varaiables dependientes basada en cualquier medida de distancia.</li>
</ul>
</section>
<section id="consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica.-1" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="consideraciones-para-aplicar-el-análisis-a-una-matriz-de-datos-básica.-1"><span class="header-section-number">1.2.2</span> Consideraciones para aplicar el análisis a una matriz de datos básica.</h3>
<p>Para poder aplicar el análisis es importante:</p>
<ol type="1">
<li>Tener más de una variable de respuesta ó dependientes a comparar.</li>
<li>Que las variables dependeientes a comparar no se ajusten a la distribucón normal-p variante para al menos uno de las poblaciones.</li>
<li>Seleccionar una medida de distancia apropiada para los datos.</li>
</ol>
</section>
</section>
</section>
<section id="materiales." class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Materiales.</h1>
<ul>
<li>Matriz de datos básica de la Guía.
<ul>
<li>iris: Para ejemplificar como se realizan ambos análisis con RStudio usaremos la base de datos <span style="color: #F84F00;">“iris”</span> incorporada dentro del ambiente de R, que contiene diversas mediciones en cm realizadas en 150 lirios de tres especies por ronald Fisher que aparecen registradas en su artículo &lt;&lt;The use of multiple measurements in taxonomic problems<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>&gt;&gt;</li>
<li><a href="https://campusvirtual.unimagdalena.edu.co/d2l/common/viewFile.d2lfile/Content/L2NvbnRlbnQvZW5mb3JjZWQvMTE0ODI1LTM4RC0yMDQzODAzLTEtMjAyNDEvbGVhZl9Mb2MueGxzeA/leaf_Loc.xlsx?ou=114825">leaf_loc</a>: contiene parte de la información de un estudio realizado por Reich et al.&nbsp;(1999) donde se examinaron generalidades de los rasgos de las hojas de diferentes especies en una variedad de ecosistemas y regiones geográficas. La matriz dispone de la información de las hojas colectadas en 3 localidades para diversas especies vegetales de árboles, sobre las cuales se midieron cinco variables de respuesta: área foliar específica, concentración de nitrógeno foliar, capacidad fotosintética neta basada en masa, capacidad fotosintética neta basada en área y conductancia difusiva foliar a capacidad fotosintética.</li>
</ul></li>
<li>Matriz de datos básica para la clase:
<ul>
<li><p><a href="https://campusvirtual.unimagdalena.edu.co/d2l/common/viewFile.d2lfile/Content/L2NvbnRlbnQvZW5mb3JjZWQvMTE0ODI1LTM4RC0yMDQzODAzLTEtMjAyNDEvVGV4YXNfVHVydGxlLnhsc3g/Texas_Turtle.xlsx?ou=114825">Texas_Tortugas</a>: Las matrices en el archivo de Excel hacen parte del trabajo realizado por [brown &amp; brown. (2020)] quienes tomaron muestras de poblaciones de tortugas de agua dulce en 66 sitios en el sur, centro y oeste de Texas, EE. UU. Los sitios de muestreo incluyeron estanques, lagos, resacas, canales y ríos usando para las capturas redes de aro con cebo (66 sitios) y trampas para tomar el sol (3 sitios), y captura manual de manera oportunista en hábitat terrestre. En cada ejemplar se medio el largo y ancho del caparazón, el largo y ancho del plastrón, la profundidad del cuerpo y el peso.</p></li>
<li><p><a href="https://campusvirtual.unimagdalena.edu.co/d2l/common/viewFile.d2lfile/Content/L2NvbnRlbnQvZW5mb3JjZWQvMTE0ODI1LTM4RC0yMDQzODAzLTEtMjAyNDEvQ29saWJyaS54bHN4/Colibri.xlsx?ou=114825">Colibris</a>: La matriz en el archivo de Excel corresponden a mediciones morfométricas tomadas en 130 colibríes repartidos entre 4 especies distinguiendo entre machos y hembras, que se registrán en la Sabana de Bogotá.</p></li>
</ul></li>
<li>Scripts: <a href="https://campusvirtual.unimagdalena.edu.co/d2l/common/viewFile.d2lfile/Content/L2NvbnRlbnQvZW5mb3JjZWQvMTc0MzUxLTM4RC0zLTAyMDQzODAzLTEtMjAyNDIvU2NyaXB0X3FtZFBDSC5xbWQ/Script_qmdPCH.qmd?ou=174351">Rmd-CHipotesis</a></li>
</ul>
</section>
<section id="pasos-previos." class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Pasos previos.</h1>
<section id="cargue-las-líbrerías." class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="cargue-las-líbrerías."><span class="header-section-number">3.1</span> 1. Cargue las líbrerías.</h2>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MVN)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(biotools)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="importe-los-datos." class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="importe-los-datos."><span class="header-section-number">3.2</span> 2. Importe los datos.</h2>
<p>La base de datos <span style="color: #F84F00;">“iris”</span> se encuentra incorporada dentro del ambiente de R, y contiene diversas mediciones en cm realizadas en 150 lirios de tres especies. Para cada individuo analizado se midieron las siguientes variables:</p>
<p><span style="align: center;"> <strong>Tabla 1.</strong></span></p>
<p><em>Descripción de las variables</em> </p>
<table class="table">
<thead>
<tr class="header">
<th>Variables</th>
<th>Unidad de mediciÃ³n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sepal.Length</td>
<td>Largo del sépalo (cm).</td>
</tr>
<tr class="even">
<td>Sepal.Width</td>
<td>Ancho del sépalo (cm).</td>
</tr>
<tr class="odd">
<td>Petal.Length</td>
<td>Largo del pétalo (cm).</td>
</tr>
<tr class="even">
<td>Petal.Width</td>
<td>Ancho del pétalo (cm).</td>
</tr>
<tr class="odd">
<td>Species</td>
<td>Especie (Setosa, Virginica, versicolor)</td>
</tr>
</tbody>
</table>
<p>Para trabajar con el conjunto solo hace falta escribir el nombre de la base de datos directamente en la consola <strong>iris</strong>. Visualizaremos los primeros 6 datos de la matriz con la función <code>"head()"</code></p>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
</div>
</section>
</section>
<section id="análisis-de-varianza-multivariado-manova" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Análisis de varianza multivariado (MANOVA)</h1>
<p><strong>¿Cómo abordar el análisis?</strong></p>
<ol type="1">
<li>Verifique el cumplimiento de los supuestos ó requerimientos.</li>
<li>Efecute el algoritmo.</li>
</ol>
<section id="paso-1.-verificación-de-los-supuesto-ó-requerimientos." class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="paso-1.-verificación-de-los-supuesto-ó-requerimientos."><span class="header-section-number">4.1</span> Paso 1. Verificación de los supuesto ó requerimientos.</h2>
<p>Las 4 variables correspondientes a las mediciones son variables métricas por lo que podríamos considerar las 4 en la comparación. Para verificar si las variables dependientes de cada especie se ajustan a la distribución normal p-variante con matrices de varianzas - covarianza, usaremos los test de normalidad de mardia y box’s M ambos empleando la función <code>"mvn()"</code> y <code>"boxM()"</code> ubicadas en las librerías <code>"MVN"</code> y <code>"biotools"</code> respectivamente. Primero realizaremos los test considerando todas las variables, luego solo la medidas de los sépalos y luego transformando las medidas de los sépalos al log10. Recuerde que la matriz tiene 150 UE’s donde de la 1:50 corresponden a la especie setosa, de la 51:100 a la especie versicolor y de la 101:150 a la especie virginica.</p>
<section id="supuesto-de-normalidad-p-variante-por-grupo." class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="supuesto-de-normalidad-p-variante-por-grupo."><span class="header-section-number">4.1.1</span> Supuesto de normalidad p-variante por grupo.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Todas las variables.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> iris[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality <span class="co">#setosa</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test        Statistic           p value Result
1 Mardia Skewness 25.6643445196298 0.177185884467652    YES
2 Mardia Kurtosis 1.29499223711605 0.195322907441935    YES
3             MVN             &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> iris[<span class="dv">51</span><span class="sc">:</span><span class="dv">100</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality <span class="co">#versicolor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test         Statistic           p value Result
1 Mardia Skewness  25.1850115362466 0.194444483140265    YES
2 Mardia Kurtosis -0.57186635893429 0.567412516528727    YES
3             MVN              &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> iris[<span class="dv">101</span><span class="sc">:</span><span class="dv">150</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality <span class="co">#virginica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test         Statistic           p value Result
1 Mardia Skewness  26.2705981752915 0.157059707690356    YES
2 Mardia Kurtosis 0.152614173978342 0.878702546726567    YES
3             MVN              &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datos de los sépalos sin transformar.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> iris[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality <span class="co">#setosa</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test          Statistic           p value Result
1 Mardia Skewness  0.759503524380438 0.943793240544741    YES
2 Mardia Kurtosis 0.0934600553610254 0.925538081956867    YES
3             MVN               &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> iris[<span class="dv">51</span><span class="sc">:</span><span class="dv">100</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality <span class="co">#versicolor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test         Statistic           p value Result
1 Mardia Skewness  1.76081423820927 0.779643267719773    YES
2 Mardia Kurtosis -0.90648685799867 0.364678217772254    YES
3             MVN              &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> iris[<span class="dv">101</span><span class="sc">:</span><span class="dv">150</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality <span class="co">#virginica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test         Statistic           p value Result
1 Mardia Skewness  5.55961530185445 0.234538733806549    YES
2 Mardia Kurtosis 0.518439311354541 0.604151792783842    YES
3             MVN              &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datos del sépalo transformados al log10</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> <span class="fu">log10</span>(iris[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]),<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality<span class="co">#versicolor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test        Statistic           p value Result
1 Mardia Skewness 6.92773595793483 0.139756685522801    YES
2 Mardia Kurtosis 1.48270243556113 0.138153487258629    YES
3             MVN             &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> <span class="fu">log10</span>(iris[<span class="dv">51</span><span class="sc">:</span><span class="dv">100</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]),<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test        Statistic           p value Result
1 Mardia Skewness 4.20578758043929 0.378871328783244    YES
2 Mardia Kurtosis -0.5161666429526 0.605738025673362    YES
3             MVN             &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(<span class="at">data =</span> <span class="fu">log10</span>(iris[<span class="dv">101</span><span class="sc">:</span><span class="dv">150</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]),<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality<span class="co">#virginica</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test         Statistic           p value Result
1 Mardia Skewness  4.03301040221599 0.401556811291949    YES
2 Mardia Kurtosis 0.651270054856751 0.514872175139625    YES
3             MVN              &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
</div>
</section>
<section id="supuesto-de-homocedasticidad-de-las-matrices-var--cov." class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="supuesto-de-homocedasticidad-de-las-matrices-var--cov."><span class="header-section-number">4.1.2</span> Supuesto de homocedasticidad de las matrices var- cov.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Todas las variables.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxM</span>(<span class="at">data =</span> iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>],<span class="at">grouping =</span>iris[,<span class="dv">5</span>] )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box's M-test for Homogeneity of Covariance Matrices

data:  iris[, 1:4]
Chi-Sq (approx.) = 140.94, df = 20, p-value &lt; 2.2e-16</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datos de los sépalos sin transformar.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxM</span>(<span class="at">data =</span> iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="at">grouping =</span>iris[,<span class="dv">5</span>] )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box's M-test for Homogeneity of Covariance Matrices

data:  iris[, 1:2]
Chi-Sq (approx.) = 35.655, df = 6, p-value = 3.217e-06</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Datos del sépalo transformados al log10</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxM</span>(<span class="at">data =</span> <span class="fu">log10</span>(iris[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]),<span class="at">grouping =</span>iris[,<span class="dv">5</span>] )<span class="co">#setosa</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box's M-test for Homogeneity of Covariance Matrices

data:  log10(iris[, 1:2])
Chi-Sq (approx.) = 16.182, df = 6, p-value = 0.01281</code></pre>
</div>
</div>
<p>Ya que el MANOVA requiere que se cumplan tanto el supuesto de normalidad multivariada como el de homocedasticidad en las matrices de var - cov para las variables consideradas entre las poblaciones, de acuerdo con las salidas abordaremos el análisis con las mediciones de los sépalos transformadas al log10, para las que fue posible verificar el ajuste a la distribución normal p-variante de las mediciones del ancho y largo de sépalos empleando el test de mardia, al no evidenciarse asimérica significativa ni para la especie setosa, <span class="math inline">\(\chi^{2}(4,N=50)=6.93, p=0.14\)</span>, ni para la especie verisicolor <span class="math inline">\(\chi^{2}(4,N=50)=4.21, p=0.38\)</span>, ni para la especie virginica <span class="math inline">\(\chi^{2}(4,N=50)=4.03, p=0.40\)</span>, ni variación significativa con respecto al vector de medias, <span class="math inline">\(\ z=1.48, p=0.14\)</span> para setosa, <span class="math inline">\(\ z=-0.52, p=0.61\)</span> para versicolor y <span class="math inline">\(\ z=0.65, p=0.51\)</span> para virginica. Además el test M de box no reflejó diferencias aparentes entre las matrices de varianza - covarianzas de las tres especies, <span class="math inline">\(\chi{2}(6)=16.182, p=0.013\)</span>.</p>
<p><strong>Nota:</strong> recuerde que según Hahs-Vaughn (2016), valores p menores a 0.001 se consideran significantes para la prueba M de box<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
</section>
<section id="supuesto-de-linealidad-y-multicolinealidad." class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="supuesto-de-linealidad-y-multicolinealidad."><span class="header-section-number">4.1.3</span> Supuesto de linealidad y multicolinealidad.</h3>
<p>Para verificar si existe linealidad entre las variables dependientes sin evidencia de multicolinealidad al 100% en las tres poblaciones (especies), analizaremos la correlación entre las variables dependientes empleando la función <code>"cor_test()"</code> ubicada en la librería <code>"rstatix"</code>, recuerde que correlaciones por encima de 0.9 se consideran significativas para multicolinealidad al 100%.</p>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Añadir datos transformados a la matriz</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Sepal.LengthLog10<span class="ot">&lt;-</span><span class="fu">log10</span>(iris<span class="sc">$</span>Sepal.Length) </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Sepal.WidthLog10<span class="ot">&lt;-</span><span class="fu">log10</span>(iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Test.</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species)<span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor_test</span>(Sepal.LengthLog10,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>           Sepal.WidthLog10) <span class="sc">%&gt;%</span> </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Species              var1             var2  cor statistic        p
1     setosa Sepal.LengthLog10 Sepal.WidthLog10 0.73  7.398129 1.81e-09
2 versicolor Sepal.LengthLog10 Sepal.WidthLog10 0.53  4.311844 8.01e-05
3  virginica Sepal.LengthLog10 Sepal.WidthLog10 0.46  3.600478 7.51e-04
   conf.low conf.high  method
1 0.5666952 0.8380009 Pearson
2 0.2931550 0.7032970 Pearson
3 0.2097006 0.6553610 Pearson</code></pre>
</div>
</div>
<p>Con el análisis de correlaciones se evidenció una relación lineal directamente proporcional significativa entre estas dos medidas para las tres especie, donde la mayor correlación lineal se muestra entre el ancho y largo de los sépalos de la especie setosa, <span class="math inline">\(\rho=-0.73\)</span> (<span class="math inline">\(\ t(50)=7.40, p&lt;0.05\)</span>), y la menor entre el ancho y largo de los sépalos de la especievirginica, <span class="math inline">\(\rho=-0.46\)</span> (<span class="math inline">\(\ t(50)=3.6, p&lt;0.05\)</span>), sin que tal correlación supere el 0.9.</p>
</section>
<section id="supuesto-de-datos-atípicos-influyentes." class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="supuesto-de-datos-atípicos-influyentes."><span class="header-section-number">4.1.4</span> Supuesto de datos atípicos influyentes.</h3>
<p>Por último verificaremos si el conjunto cuenta con observaciones atípicas influyentes a nivel multivariado, para ellos emplearemos la función <code>"mahalanobis_distance()"</code> vista en la clase de exploración de datos. Recuerde que la función toma como valor crítico para <span class="math inline">\(\ D^{2}\)</span>, el cuántil en la distibución chi-cuadrado tal que <span class="math inline">\(\chi{2}(0.999,p)\)</span> donde p es el número de variables.</p>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>iris[,<span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>] <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mahalanobis_distance</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    Sepal.LengthLog10 Sepal.WidthLog10 mahal.dist is.outlier
1           0.7075702        0.5440680      1.649      FALSE
2           0.6901961        0.4771213      1.423      FALSE
3           0.6720979        0.5051500      2.218      FALSE
4           0.6627578        0.4913617      2.639      FALSE
5           0.6989700        0.5563025      2.289      FALSE
6           0.7323938        0.5910646      3.228      FALSE
7           0.6627578        0.5314789      3.043      FALSE
8           0.6989700        0.5314789      1.562      FALSE
9           0.6434527        0.4623980      4.029      FALSE
10          0.6901961        0.4913617      1.386      FALSE
11          0.7323938        0.5682017      2.084      FALSE
12          0.6812412        0.5314789      2.199      FALSE
13          0.6812412        0.4771213      1.794      FALSE
14          0.6334685        0.4771213      4.507      FALSE
15          0.7634280        0.6020600      3.856      FALSE
16          0.7558749        0.6434527      6.878      FALSE
17          0.7323938        0.5910646      3.228      FALSE
18          0.7075702        0.5440680      1.649      FALSE
19          0.7558749        0.5797836      2.536      FALSE
20          0.7075702        0.5797836      3.050      FALSE
21          0.7323938        0.5314789      0.822      FALSE
22          0.7075702        0.5682017      2.522      FALSE
23          0.6627578        0.5563025      3.716      FALSE
24          0.7075702        0.5185139      1.057      FALSE
25          0.6812412        0.5314789      2.199      FALSE
26          0.6989700        0.4771213      1.100      FALSE
27          0.6989700        0.5314789      1.562      FALSE
28          0.7160033        0.5440680      1.450      FALSE
29          0.7160033        0.5314789      1.110      FALSE
30          0.6720979        0.5051500      2.218      FALSE
31          0.6812412        0.4913617      1.750      FALSE
32          0.7323938        0.5314789      0.822      FALSE
33          0.7160033        0.6127839      4.777      FALSE
34          0.7403627        0.6232493      5.258      FALSE
35          0.6901961        0.4913617      1.386      FALSE
36          0.6989700        0.5051500      1.145      FALSE
37          0.7403627        0.5440680      1.093      FALSE
38          0.6901961        0.5563025      2.570      FALSE
39          0.6434527        0.4771213      3.839      FALSE
40          0.7075702        0.5314789      1.314      FALSE
41          0.6989700        0.5440680      1.890      FALSE
42          0.6532125        0.3617278      7.710      FALSE
43          0.6434527        0.5051500      3.791      FALSE
44          0.6989700        0.5440680      1.890      FALSE
45          0.7075702        0.5797836      3.050      FALSE
46          0.6812412        0.4771213      1.794      FALSE
47          0.7075702        0.5797836      3.050      FALSE
48          0.6627578        0.5051500      2.682      FALSE
49          0.7242759        0.5682017      2.191      FALSE
50          0.6989700        0.5185139      1.311      FALSE
51          0.8450980        0.5051500      2.116      FALSE
52          0.8061800        0.5051500      0.734      FALSE
53          0.8388491        0.4913617      1.651      FALSE
54          0.7403627        0.3617278      4.016      FALSE
55          0.8129134        0.4471580      0.887      FALSE
56          0.7558749        0.4471580      0.324      FALSE
57          0.7993405        0.5185139      0.821      FALSE
58          0.6901961        0.3802112      4.496      FALSE
59          0.8195439        0.4623980      0.908      FALSE
60          0.7160033        0.4313638      1.360      FALSE
61          0.6989700        0.3010300     10.253      FALSE
62          0.7708520        0.4771213      0.021      FALSE
63          0.7781513        0.3424227      4.973      FALSE
64          0.7853298        0.4623980      0.207      FALSE
65          0.7481880        0.4623980      0.160      FALSE
66          0.8260748        0.4913617      1.161      FALSE
67          0.7481880        0.4771213      0.061      FALSE
68          0.7634280        0.4313638      0.642      FALSE
69          0.7923917        0.3424227      5.032      FALSE
70          0.7481880        0.3979400      1.932      FALSE
71          0.7708520        0.5051500      0.185      FALSE
72          0.7853298        0.4471580      0.396      FALSE
73          0.7993405        0.3979400      1.995      FALSE
74          0.7853298        0.4471580      0.396      FALSE
75          0.8061800        0.4623980      0.559      FALSE
76          0.8195439        0.4771213      0.872      FALSE
77          0.8325089        0.4471580      1.485      FALSE
78          0.8260748        0.4771213      1.083      FALSE
79          0.7781513        0.4623980      0.140      FALSE
80          0.7558749        0.4149733      1.179      FALSE
81          0.7403627        0.3802112      2.925      FALSE
82          0.7403627        0.3802112      2.925      FALSE
83          0.7634280        0.4313638      0.642      FALSE
84          0.7781513        0.4313638      0.666      FALSE
85          0.7323938        0.4771213      0.252      FALSE
86          0.7781513        0.5314789      0.784      FALSE
87          0.8260748        0.4913617      1.161      FALSE
88          0.7993405        0.3617278      3.837      FALSE
89          0.7481880        0.4771213      0.061      FALSE
90          0.7403627        0.3979400      2.047      FALSE
91          0.7403627        0.4149733      1.359      FALSE
92          0.7853298        0.4771213      0.141      FALSE
93          0.7634280        0.4149733      1.138      FALSE
94          0.6989700        0.3617278      5.260      FALSE
95          0.7481880        0.4313638      0.741      FALSE
96          0.7558749        0.4771213      0.017      FALSE
97          0.7558749        0.4623980      0.109      FALSE
98          0.7923917        0.4623980      0.300      FALSE
99          0.7075702        0.3979400      2.886      FALSE
100         0.7558749        0.4471580      0.324      FALSE
101         0.7993405        0.5185139      0.821      FALSE
102         0.7634280        0.4313638      0.642      FALSE
103         0.8512583        0.4771213      2.112      FALSE
104         0.7993405        0.4623980      0.418      FALSE
105         0.8129134        0.4771213      0.681      FALSE
106         0.8808136        0.4771213      3.756      FALSE
107         0.6901961        0.3979400      3.566      FALSE
108         0.8633229        0.4623980      2.725      FALSE
109         0.8260748        0.3979400      2.588      FALSE
110         0.8573325        0.5563025      4.343      FALSE
111         0.8129134        0.5051500      0.914      FALSE
112         0.8061800        0.4313638      1.034      FALSE
113         0.8325089        0.4771213      1.313      FALSE
114         0.7558749        0.3979400      1.851      FALSE
115         0.7634280        0.4471580      0.298      FALSE
116         0.8061800        0.5051500      0.734      FALSE
117         0.8129134        0.4771213      0.681      FALSE
118         0.8864907        0.5797836      7.440      FALSE
119         0.8864907        0.4149733      4.807      FALSE
120         0.7781513        0.3424227      4.973      FALSE
121         0.8388491        0.5051500      1.839      FALSE
122         0.7481880        0.4471580      0.382      FALSE
123         0.8864907        0.4471580      4.201      FALSE
124         0.7993405        0.4313638      0.905      FALSE
125         0.8260748        0.5185139      1.605      FALSE
126         0.8573325        0.5051500      2.719      FALSE
127         0.7923917        0.4471580      0.482      FALSE
128         0.7853298        0.4771213      0.141      FALSE
129         0.8061800        0.4471580      0.729      FALSE
130         0.8573325        0.4771213      2.412      FALSE
131         0.8692317        0.4471580      3.162      FALSE
132         0.8976271        0.5797836      8.283      FALSE
133         0.8061800        0.4471580      0.729      FALSE
134         0.7993405        0.4471580      0.594      FALSE
135         0.7853298        0.4149733      1.195      FALSE
136         0.8864907        0.4771213      4.126      FALSE
137         0.7993405        0.5314789      1.149      FALSE
138         0.8061800        0.4913617      0.573      FALSE
139         0.7781513        0.4771213      0.067      FALSE
140         0.8388491        0.4913617      1.651      FALSE
141         0.8260748        0.4913617      1.161      FALSE
142         0.8388491        0.4913617      1.651      FALSE
143         0.7634280        0.4313638      0.642      FALSE
144         0.8325089        0.5051500      1.580      FALSE
145         0.8260748        0.5185139      1.605      FALSE
146         0.8260748        0.4771213      1.083      FALSE
147         0.7993405        0.3979400      1.995      FALSE
148         0.8129134        0.4771213      0.681      FALSE
149         0.7923917        0.5314789      1.003      FALSE
150         0.7708520        0.4771213      0.021      FALSE</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.999</span>,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.81551</code></pre>
</div>
</div>
<p>No hay evidencia de observaciones atípicas influyentes para ninguna de las tres especies en cuanto al tamaño de sus sépalos, <span class="math inline">\(\ D^{2}&lt;13.81\)</span></p>
</section>
</section>
<section id="paso-2.-efecución-del-algoritmo." class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="paso-2.-efecución-del-algoritmo."><span class="header-section-number">4.2</span> Paso 2. Efecución del algoritmo.</h2>
<p>El algoritmo se compone de dos parte:</p>
<ol type="1">
<li>La construcción de la tabla de MANOVA.</li>
<li>La prueba de contrastes múltiples en caso de un rechazo de la Ho.</li>
</ol>
<p>Para el primer paso emplearemos la función <code>"manova()"</code> ubicada en la librería <code>"car"</code> y para el segundo la función <code>"lsmeans()"</code> ubicada en la librería <code>"emmeans"</code>.</p>
<section id="tabla-de-manova." class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="tabla-de-manova."><span class="header-section-number">4.2.1</span> Tabla de MANOVA.</h3>
<p>A la hora de mostar la tabla de MANOVA la función dispone de 4 test <code>"Pillai"</code>,<code>"Wilks"</code>,<code>"Hotelling-Lawley"</code> y <code>"Roy"</code>. Históricamente, el estadístico de Wilks ha jugado el papel dominante en las pruebas de significación en el MANOVA porque fue el primero en derivarse y tiene conocidas aproximaciones a las distribuciones <span class="math inline">\(\chi{2}\)</span> y <span class="math inline">\(\ F\)</span>, más no implica que sea el test más robusto. En este sentido se aplica el test de:</p>
<ul>
<li><p><code>"Roy"</code>: si los vectores medios son colineales, es decir si hay evidencia de multicolinealidad entre las variables dependientes y solo en tales casos se recomienda su uso ya que es sensible a la violación del resto de supuestos<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p></li>
<li><p><code>"Pillai"</code>,<code>"Wilks"</code> ó <code>"Hotelling-Lawley":</code> si los datos provienen de poblaciones no normales que exhiben asimetría o curtosis positiva<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p></li>
<li><p><code>"Pillai"</code>: Es la más robusta de todas y especialmente util si se viola el supuesto homogeneidad de varianza-covarianza y/o si se tienen tamaños de muestra pequeños (Rencher, 2012)<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p></li>
</ul>
<p>Con el análisis buscaremos dar respuesta a la pregunta: <span style="color: #F84F00;">¿Es la especie un factor determinante de la estructura de los sépalos de los iris?</span></p>
<p>Las hipótesis a contrastar de forma génerica para el test son:</p>
<p><span class="math inline">\(\ H_0:\)</span> El vector de media de todas las poblaciones son iguales. En nuestro contexto sería que la estructura de los sépalos es la misma para las tres especies.</p>
<p><span class="math inline">\(\ H_1:\)</span> El vector de media es diferente para al menos un par de poblaciones. En nuestro contexto sería que la estructura de los sépalos es diferente entre al menos un par de especies.</p>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>modelo<span class="ot">&lt;-</span><span class="fu">manova</span>(<span class="fu">cbind</span>(Sepal.LengthLog10,Sepal.WidthLog10)<span class="sc">~</span>Species,<span class="at">data=</span>iris)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo,<span class="at">test=</span><span class="st">"Pillai"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           Df  Pillai approx F num Df den Df    Pr(&gt;F)    
Species     2 0.95302   66.904      4    294 &lt; 2.2e-16 ***
Residuals 147                                             
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>La estadística de Pillai reflejó que existe sufiente evidencia a partir de los datos para afirmar que para al menos un par de especies los sépalos son significativamente distintos en cuánto a su estructura, <span class="math inline">\(\ F(4, 294)=66.90, p&lt;0.001\)</span>.</p>
</section>
<section id="contrastes-múltiples." class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="contrastes-múltiples."><span class="header-section-number">4.2.2</span> Contrastes múltiples.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Vector de medias</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">mean</span>(Sepal.LengthLog10),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mean</span>(Sepal.WidthLog10))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  Species    `mean(Sepal.LengthLog10)` `mean(Sepal.WidthLog10)`
  &lt;fct&gt;                          &lt;dbl&gt;                    &lt;dbl&gt;
1 setosa                         0.698                    0.532
2 versicolor                     0.772                    0.440
3 virginica                      0.817                    0.471</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Contraste</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>d<span class="ot">&lt;-</span><span class="fu">lsmeans</span>(<span class="fu">lm</span>(<span class="fu">cbind</span>(Sepal.LengthLog10,Sepal.WidthLog10)<span class="sc">~</span>Species,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data=</span>iris),<span class="st">"Species"</span>) </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">test</span>(<span class="fu">contrast</span>(d,<span class="st">"pairwise"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> contrast               estimate      SE  df t.ratio p.value
 setosa - versicolor     0.00965 0.00761 147   1.268  0.4155
 setosa - virginica     -0.02840 0.00761 147  -3.730  0.0008
 versicolor - virginica -0.03805 0.00761 147  -4.998  &lt;.0001

Results are averaged over the levels of: rep.meas 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#GRÁFICA. </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">as.data.frame</span>(d),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>Species,<span class="at">y=</span>lsmean,<span class="at">color=</span>Species))<span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower.CL, <span class="at">ymax=</span>upper.CL),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)<span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">pch=</span><span class="dv">20</span>,<span class="at">size=</span><span class="fl">2.2</span>,<span class="at">color=</span><span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Set2"</span>)<span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)<span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Especies"</span>,<span class="at">y=</span><span class="st">"Medias de mínimos cuadrados"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MAVOVA-perMANOVA_RStudio_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="624"></p>
</figure>
</div>
</div>
</div>
<p>El test de Tukey dejó en evidencia que la especie virginica tiene sépalos estadísticamente de mayor tamaño que las especies versicolor, <span class="math inline">\(\ p&lt;0.001\)</span> y setosa, <span class="math inline">\(\ p&lt;0.001\)</span>. No se observaron diferencias aparentes entre la estructura de los sépalo de las dos últimas especies,<span class="math inline">\(\ p=0.42\)</span>.</p>
</section>
</section>
</section>
<section id="análisis-de-varianza-multivariado-permutacional-permanova." class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Análisis de varianza multivariado permutacional (perMANOVA).</h1>
<p><strong>¿Cómo abordar el análisis?</strong></p>
<ol type="1">
<li>Verificar el supuesto de normalidad p-variante y homocedasticidad por grupo.</li>
<li>Efecute el algoritmo.</li>
</ol>
<section id="pasos-previos.-1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="pasos-previos.-1"><span class="header-section-number">5.1</span> Pasos previos.</h2>
<section id="cargue-las-líbrerías.-1" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="cargue-las-líbrerías.-1"><span class="header-section-number">5.1.1</span> 1. Cargue las líbrerías.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MVN)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vegan)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RVAideMemoire)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="importe-los-datos.-1" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="importe-los-datos.-1"><span class="header-section-number">5.1.2</span> 2. Importe los datos.</h3>
<p>La base de datos <span style="color: #F84F00;">“leaf_loc”</span> contiene parte de la información de un estudio realizado por Reich et al.&nbsp;(1999) donde se examinaron generalidades de los rasgos de las hojas de diferentes especies en una variedad de ecosistemas y regiones geográficas. La matriz dispone de la información de las hojas colectadas en 3 localidades para diversas especies vegetales de árboles, sobre las cuales se midieron cinco variables de respuesta:área foliar específica, concentración de nitrógeno foliar, capacidad fotosintética neta basada en masa, capacidad fotosintética neta basada en área y conductancia difusiva foliar a capacidad fotosintética. A continuación, se relacionan las variables asociadas en la matriz de datos.</p>
<p><span style="align: center;"> <strong>Tabla 1.</strong></span></p>
<p><em>Descripción de las variables</em> </p>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th>Variables</th>
<th>Unidad de mediciÃ³n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Localitation</td>
<td>Localidad.</td>
</tr>
<tr class="even">
<td>Specie</td>
<td>Especie</td>
</tr>
<tr class="odd">
<td>Funcional</td>
<td>Rasgo funcional</td>
</tr>
<tr class="even">
<td>Type.leaf</td>
<td>Tipo de hoja</td>
</tr>
<tr class="odd">
<td>SLA</td>
<td>área foliar específica (cm2/g)</td>
</tr>
<tr class="even">
<td>N</td>
<td>concentración de nitrógeno foliar (mg/g)</td>
</tr>
<tr class="odd">
<td>AMASS</td>
<td>capacidad fotosintética basada en masa (nmol·g-1·s-1)</td>
</tr>
<tr class="even">
<td>AAREA</td>
<td>capacidad fotosintética basada en área. (µmol· m-2 ·s-1)</td>
</tr>
<tr class="odd">
<td>GS</td>
<td>conductancia difusiva foliar a capacidad fotosintética (mmol· m-2 ·s-1)</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>leaf <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="fu">file.choose</span>())</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(leaf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  Localitation   Specie        Funcional Type.leaf   SLA     N AMASS AAREA    GS
  &lt;chr&gt;          &lt;chr&gt;         &lt;chr&gt;     &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 North Carolina Robinia pseu… tree      broad     264    43.3 243.    9.4   297
2 North Carolina Acer rubrum   tree      broad     160    18.4 125     7.7   237
3 North Carolina Liriodendron… tree      broad     165    22.4 170    10.2   450
4 North Carolina Quercus cocc… tree      broad     118    17.3 111     9.7   338
5 North Carolina Pinus strobus tree      needle     92    13.5  50.6   6     198
6 North Carolina Pinus rigida  tree      needle     48.9  11.6  55.7  11.3   317</code></pre>
</div>
</div>
</section>
</section>
<section id="paso-1.-verificación-del-supuestos." class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="paso-1.-verificación-del-supuestos."><span class="header-section-number">5.2</span> Paso 1. Verificación del supuestos.</h2>
<section id="supuesto-de-normalidad-p-variante-por-grupo.-1" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="supuesto-de-normalidad-p-variante-por-grupo.-1"><span class="header-section-number">5.2.1</span> 1.1 Supuesto de normalidad p variante por grupo.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(leaf[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test          Statistic           p value Result
1 Mardia Skewness   43.5406465737089 0.152402425386367    YES
2 Mardia Kurtosis -0.953093743267611 0.340542575945523    YES
3             MVN               &lt;NA&gt;              &lt;NA&gt;    YES</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(leaf[<span class="dv">9</span><span class="sc">:</span><span class="dv">28</span>,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test        Statistic              p value Result
1 Mardia Skewness 84.7932432287157 5.13227485850579e-06     NO
2 Mardia Kurtosis  1.9342114503286   0.0530871351338096    YES
3             MVN             &lt;NA&gt;                 &lt;NA&gt;     NO</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mvn</span>(leaf[<span class="dv">29</span><span class="sc">:</span><span class="dv">44</span>,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>],<span class="at">mvnTest =</span> <span class="st">"mardia"</span>)<span class="sc">$</span>multivariateNormality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Test         Statistic             p value Result
1 Mardia Skewness  59.2304744463534 0.00642500934015118     NO
2 Mardia Kurtosis 0.405098802575199    0.68540488662858    YES
3             MVN              &lt;NA&gt;                &lt;NA&gt;     NO</code></pre>
</div>
</div>
</section>
<section id="supuesto-de-homocedasticidad-p-variante." class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="supuesto-de-homocedasticidad-p-variante."><span class="header-section-number">5.2.2</span> 1.2 Supuesto de homocedasticidad p variante.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxM</span>(<span class="at">data =</span> leaf[,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>],<span class="at">grouping =</span>leaf<span class="sc">$</span>Localitation )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box's M-test for Homogeneity of Covariance Matrices

data:  leaf[, 5:9]
Chi-Sq (approx.) = 94.62, df = 30, p-value = 1.288e-08</code></pre>
</div>
</div>
<p>Como se evidencia en las salidas anteriores no fue posible verificar el ajuste a la distribución normal p-variante de las mediciones para las diferentes rasgos funcionales de las hojas empleando el test de mardia en todos los grupos, al evidenciarse asimérica significativa en la distribución p variante en las mediciones colectadas en la localidad 2 (Venezuela) , <span class="math inline">\(\chi^{2}(5,N=20)=84.793, p&lt;0.0001\)</span>; y la localidad 3 (Wisconsisn), <span class="math inline">\(\chi^{2}(5,N=16)=59.23, p=0.0064\)</span>. Además el test M de box reflejó diferencias estadísticas entre las matrices de varianza - covarianzas de las tres localidades, <span class="math inline">\(\chi{2}(30)=94.62, p&lt;0.0001\)</span>.</p>
<p><strong>Nota:</strong> recuerde que según Hahs-Vaughn (2016), valores p menores a 0.001 se consideran significantes para la prueba M de box<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
</section>
</section>
<section id="paso-2.-efecución-del-algoritmo" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="paso-2.-efecución-del-algoritmo"><span class="header-section-number">5.3</span> Paso 2. Efecución del algoritmo</h2>
<p>Al igual que en el MANOVA el algoritmo se compone de dos parte:</p>
<ol type="1">
<li>La construcción de la tabla de perMANOVA con la distancia escogida.</li>
<li>La prueba de contrastes múltiples en caso de un rechazo de la Ho.</li>
</ol>
<p>Para la primera parte usaremos la función <code>"adonis()"</code> ubicada en la librería <code>"vegan"</code> indicando como medida de distancia <code>"euclidean"</code> al tratarse las variables dependiente de medidas métricas. Para la segunda parte emplearemos la función <code>"pairwise.perm.manova()"</code> ubicada en la librería <code>"RVAideMemoire"</code>.</p>
<p>Las hipótesis a contrastar de forma génerica para el test son:</p>
<p><span class="math inline">\(\ H_0:\)</span> No hay diferencias en las posiciones de los centroides de los grupos en el espacio de la medida de disimilitud elegida.</p>
<p><span class="math inline">\(\ H_1:\)</span> Hay diferencias en las posiciones de los centroides de los grupos en el espacio de la medida de disimilitud elegida.</p>
<section id="tabla-de-per-manova." class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="tabla-de-per-manova."><span class="header-section-number">5.3.1</span> Tabla de per-MANOVA.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">adonis2</span>(leaf[,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>]<span class="sc">~</span>Localitation,<span class="at">data=</span>leaf, <span class="at">method =</span> <span class="st">"euclidean"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Permutation test for adonis under reduced model
Permutation: free
Number of permutations: 999

adonis2(formula = leaf[, 5:9] ~ Localitation, data = leaf, method = "euclidean")
         Df SumOfSqs      R2      F Pr(&gt;F)  
Model     2  1085072 0.15144 3.6585  0.028 *
Residual 41  6080048 0.84856                
Total    43  7165120 1.00000                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="contrastes-múltiples.-1" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="contrastes-múltiples.-1"><span class="header-section-number">5.3.2</span> Contrastes múltiples.</h3>
<div class="cell" data-layout-align="center">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Contrastes</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.perm.manova</span>(leaf[,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>],leaf<span class="sc">$</span>Localitation,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">p.method =</span> <span class="st">"bonf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |=                                                                     |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |==========                                                            |  15%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |===============                                                       |  21%
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |================                                                      |  23%
  |                                                                            
  |=================                                                     |  24%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |====================                                                  |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |=========================                                             |  36%
  |                                                                            
  |==========================                                            |  37%
  |                                                                            
  |===========================                                           |  38%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |=============================                                         |  41%
  |                                                                            
  |=============================                                         |  42%
  |                                                                            
  |==============================                                        |  43%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |================================                                      |  46%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |==================================                                    |  48%
  |                                                                            
  |==================================                                    |  49%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |====================================                                  |  52%
  |                                                                            
  |=====================================                                 |  53%
  |                                                                            
  |======================================                                |  54%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |=========================================                             |  58%
  |                                                                            
  |=========================================                             |  59%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |============================================                          |  63%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |==============================================                        |  66%
  |                                                                            
  |===============================================                       |  67%
  |                                                                            
  |================================================                      |  68%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |==================================================                    |  72%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |=====================================================                 |  76%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |=======================================================               |  79%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |=========================================================             |  82%
  |                                                                            
  |==========================================================            |  83%
  |                                                                            
  |===========================================================           |  84%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |============================================================          |  86%
  |                                                                            
  |=============================================================         |  87%
  |                                                                            
  |==============================================================        |  88%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |================================================================      |  92%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |==================================================================    |  95%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |===================================================================== |  98%
  |                                                                            
  |===================================================================== |  99%
  |                                                                            
  |======================================================================| 100%

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |=                                                                     |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |==========                                                            |  15%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |===============                                                       |  21%
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |================                                                      |  23%
  |                                                                            
  |=================                                                     |  24%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |====================                                                  |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |=========================                                             |  36%
  |                                                                            
  |==========================                                            |  37%
  |                                                                            
  |===========================                                           |  38%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |=============================                                         |  41%
  |                                                                            
  |=============================                                         |  42%
  |                                                                            
  |==============================                                        |  43%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |================================                                      |  46%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |==================================                                    |  48%
  |                                                                            
  |==================================                                    |  49%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |====================================                                  |  52%
  |                                                                            
  |=====================================                                 |  53%
  |                                                                            
  |======================================                                |  54%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |=========================================                             |  58%
  |                                                                            
  |=========================================                             |  59%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |============================================                          |  63%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |==============================================                        |  66%
  |                                                                            
  |===============================================                       |  67%
  |                                                                            
  |================================================                      |  68%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |==================================================                    |  72%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |=====================================================                 |  76%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |=======================================================               |  79%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |=========================================================             |  82%
  |                                                                            
  |==========================================================            |  83%
  |                                                                            
  |===========================================================           |  84%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |============================================================          |  86%
  |                                                                            
  |=============================================================         |  87%
  |                                                                            
  |==============================================================        |  88%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |================================================================      |  92%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |==================================================================    |  95%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |===================================================================== |  98%
  |                                                                            
  |===================================================================== |  99%
  |                                                                            
  |======================================================================| 100%

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |=                                                                     |   1%
  |                                                                            
  |=                                                                     |   2%
  |                                                                            
  |==                                                                    |   3%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |====                                                                  |   5%
  |                                                                            
  |====                                                                  |   6%
  |                                                                            
  |=====                                                                 |   7%
  |                                                                            
  |======                                                                |   8%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=======                                                               |  10%
  |                                                                            
  |========                                                              |  11%
  |                                                                            
  |========                                                              |  12%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |==========                                                            |  14%
  |                                                                            
  |==========                                                            |  15%
  |                                                                            
  |===========                                                           |  16%
  |                                                                            
  |============                                                          |  17%
  |                                                                            
  |=============                                                         |  18%
  |                                                                            
  |=============                                                         |  19%
  |                                                                            
  |==============                                                        |  20%
  |                                                                            
  |===============                                                       |  21%
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |================                                                      |  23%
  |                                                                            
  |=================                                                     |  24%
  |                                                                            
  |==================                                                    |  25%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |===================                                                   |  27%
  |                                                                            
  |====================                                                  |  28%
  |                                                                            
  |====================                                                  |  29%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |======================                                                |  31%
  |                                                                            
  |======================                                                |  32%
  |                                                                            
  |=======================                                               |  33%
  |                                                                            
  |========================                                              |  34%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |=========================                                             |  36%
  |                                                                            
  |==========================                                            |  37%
  |                                                                            
  |===========================                                           |  38%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |============================                                          |  40%
  |                                                                            
  |=============================                                         |  41%
  |                                                                            
  |=============================                                         |  42%
  |                                                                            
  |==============================                                        |  43%
  |                                                                            
  |===============================                                       |  44%
  |                                                                            
  |================================                                      |  45%
  |                                                                            
  |================================                                      |  46%
  |                                                                            
  |=================================                                     |  47%
  |                                                                            
  |==================================                                    |  48%
  |                                                                            
  |==================================                                    |  49%
  |                                                                            
  |===================================                                   |  50%
  |                                                                            
  |====================================                                  |  51%
  |                                                                            
  |====================================                                  |  52%
  |                                                                            
  |=====================================                                 |  53%
  |                                                                            
  |======================================                                |  54%
  |                                                                            
  |======================================                                |  55%
  |                                                                            
  |=======================================                               |  56%
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |=========================================                             |  58%
  |                                                                            
  |=========================================                             |  59%
  |                                                                            
  |==========================================                            |  60%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |===========================================                           |  62%
  |                                                                            
  |============================================                          |  63%
  |                                                                            
  |=============================================                         |  64%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |==============================================                        |  66%
  |                                                                            
  |===============================================                       |  67%
  |                                                                            
  |================================================                      |  68%
  |                                                                            
  |================================================                      |  69%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |==================================================                    |  71%
  |                                                                            
  |==================================================                    |  72%
  |                                                                            
  |===================================================                   |  73%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |====================================================                  |  75%
  |                                                                            
  |=====================================================                 |  76%
  |                                                                            
  |======================================================                |  77%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |=======================================================               |  79%
  |                                                                            
  |========================================================              |  80%
  |                                                                            
  |=========================================================             |  81%
  |                                                                            
  |=========================================================             |  82%
  |                                                                            
  |==========================================================            |  83%
  |                                                                            
  |===========================================================           |  84%
  |                                                                            
  |============================================================          |  85%
  |                                                                            
  |============================================================          |  86%
  |                                                                            
  |=============================================================         |  87%
  |                                                                            
  |==============================================================        |  88%
  |                                                                            
  |==============================================================        |  89%
  |                                                                            
  |===============================================================       |  90%
  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |================================================================      |  92%
  |                                                                            
  |=================================================================     |  93%
  |                                                                            
  |==================================================================    |  94%
  |                                                                            
  |==================================================================    |  95%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |====================================================================  |  97%
  |                                                                            
  |===================================================================== |  98%
  |                                                                            
  |===================================================================== |  99%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using permutation MANOVAs (test: Pillai) 

data:  leaf[, 5:9] by leaf$Localitation
999 permutations 

          North Carolina Venezuela
Venezuela 0.066          -        
Wisconsin 0.120          0.006    

P value adjustment method: bonf </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#GRAFICA.</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FactoMineR);<span class="fu">library</span>(factoextra);<span class="fu">library</span>(ggrepel)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>acp<span class="ot">&lt;-</span><span class="fu">PCA</span>(leaf[,<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>],<span class="at">graph =</span> <span class="cn">FALSE</span>,<span class="at">ncp =</span> <span class="dv">5</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>datap<span class="ot">&lt;-</span><span class="fu">data.frame</span>(acp<span class="sc">$</span>ind<span class="sc">$</span>coord,<span class="at">Localidad=</span>leaf<span class="sc">$</span>Localitation)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>datav<span class="ot">&lt;-</span><span class="fu">data.frame</span>(acp<span class="sc">$</span>var<span class="sc">$</span>coord[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(datav)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"D1"</span>,<span class="st">"D2"</span>)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> datap,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Dim<span class="fl">.1</span>,<span class="at">y =</span> Dim<span class="fl">.2</span>))<span class="sc">+</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_ellipse</span>(<span class="at">type =</span><span class="st">"euclid"</span> ,</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">fill=</span>Localidad),</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">level =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">geom =</span> <span class="st">"polygon"</span>,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span><span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)<span class="sc">+</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>()<span class="sc">+</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"gray"</span>)<span class="sc">+</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>,<span class="at">linetype=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"gray"</span>)<span class="sc">+</span></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data=</span>datav, </span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">xend=</span>D1<span class="sc">*</span><span class="fl">1.2</span>, <span class="at">yend=</span>D2<span class="sc">*</span><span class="fl">1.2</span>),</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>               <span class="at">col=</span><span class="st">"navy"</span>,</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>               <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span><span class="fu">unit</span>(<span class="fl">0.2</span>,<span class="st">"cm"</span>)),<span class="at">size=</span><span class="fl">0.4</span>)<span class="sc">+</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">data=</span>datav,</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x=</span>D1<span class="sc">*</span><span class="fl">1.2+0.1</span>,<span class="at">y=</span>D2<span class="sc">*</span><span class="fl">1.5+0.05</span>,<span class="at">label=</span><span class="fu">rownames</span>(datav)),</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">colour=</span><span class="st">"black"</span>,<span class="at">family =</span> <span class="st">"serif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MAVOVA-perMANOVA_RStudio_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>El test permutacional reflejó que el factor localidad resulta significativo para afirmar que hay diferencias en la distribución de los centroide de los ragos foliares de los árboles, <span class="math inline">\(\ F(2, 41)=23.66, p=0.031\)</span>, determinando con la estadística pillai con ajuste bonferroni en las comparaciones multiples que en venezuelas los rasgos foliares de las especies son estadísticamente distintos al resto de localidades, (Wisconsin, <span class="math inline">\(\ p=0.006\)</span>; North carolina, <span class="math inline">\(\ p=0.048\)</span>). Esta diferencia radican en que esta localidad las hojas de los árboles tiene menor área foliar específica, concentración de nitrógeno foliar y capacidad fotosintética neta basada en masa y mayor capacidad fotosintética neta basada en área y conductancia difusiva foliar a capacidad fotosintética.</p>
</section>
</section>
</section>
<section id="práctica." class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Práctica.</h1>
<p>Replique a manera de práctica el análisis apropiado para comparar la estructura de las flores de las tres especies de lirios (todas las medidas) y con ello responda:</p>
<ol type="1">
<li>¿Qué condiciones se cumplen para el análisis con el conjunto de datos completo?</li>
<li>¿Qué test resulta apropiado para la comparación de acuerdo con la respuesta anterior?</li>
<li>¿Hay evidencia de diferencias en la flores entre las tres especies de lirios?</li>
<li>En caso de diferencias, ¿En qué especies las flores son diferentes? Explique.</li>
</ol>
</section>
<section id="material-complementario-para-profundizar." class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Material complementario para profundizar.</h1>
<ol type="1">
<li><p>Olive, David. (s. f.). MANOVA. En David. Olive, Robust Multivariate Analysis (1.a ed., pp.&nbsp;213-245). (Link: <a href="https://unimagdalena.alma.exlibrisgroup.com/leganto/public/57UMA_INST/citation/3660613530007076?auth=LDAP" class="uri">https://unimagdalena.alma.exlibrisgroup.com/leganto/public/57UMA_INST/citation/3660613530007076?auth=LDAP</a>)</p></li>
<li><p>Kassambara, A. (s. f.). One-Way MANOVA in R: The Ultimate Practical Guide - Datanovia. Datanovia. (Link: <a href="https://unimagdalena.alma.exlibrisgroup.com/leganto/public/57UMA_INST/citation/3660614640007076?auth=LDAP" class="uri">https://unimagdalena.alma.exlibrisgroup.com/leganto/public/57UMA_INST/citation/3660614640007076?auth=LDAP</a>)</p></li>
<li><p>Marti J. Anderson. (2017). Permutational Multivariate Analysis of Variance (PERMANOVA). En John Wiley &amp; Ltd.&nbsp;Sons (Eds.), Wiley StatsRef: Statistics Reference Online (pp.&nbsp;1-15). John Wiley &amp; Sons, Ltd.&nbsp;(Link: <a href="https://unimagdalena.alma.exlibrisgroup.com/leganto/public/57UMA_INST/citation/3660613530007076?auth=LDAP" class="uri">https://unimagdalena.alma.exlibrisgroup.com/leganto/public/57UMA_INST/citation/3660613530007076?auth=LDAP</a>)</p></li>
</ol>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Fisher, R. A. (1936). The use of multiple measurements in taxonomic problems.&nbsp;<em>Annals of Eugenics</em>,&nbsp;<em>7</em>(2), 179–188. <a href="https://doi.org/10.1111/j.1469-1809.1936.tb02137.x" class="uri">https://doi.org/10.1111/j.1469-1809.1936.tb02137.x</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Hahs-Vaughn, D.L. (2016). Applied Multivariate Statistical Concepts (1st ed.). Routledge. <a href="https://doi.org/10.4324/9781315816685" class="uri">https://doi.org/10.4324/9781315816685</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Rencher, Alvin C. 2012. Methods of multivariate analysis [electronic resource] . 3rd ed.&nbsp;editado por W. F. Christensen. Hoboken, N.J. : Wiley.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Rencher, Alvin C. 2012. Methods of multivariate analysis [electronic resource] . 3rd ed.&nbsp;editado por W. F. Christensen. Hoboken, N.J. : Wiley.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Rencher, Alvin C. 2012. Methods of multivariate analysis [electronic resource] . 3rd ed.&nbsp;editado por W. F. Christensen. Hoboken, N.J. : Wiley.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Hahs-Vaughn, D.L. (2016). Applied Multivariate Statistical Concepts (1st ed.). Routledge. <a href="https://doi.org/10.4324/9781315816685" class="uri">https://doi.org/10.4324/9781315816685</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>